name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: make test

    - name: Run tests with coverage
      run: make test-coverage

    - name: Format check
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted:"
          gofmt -s -l .
          exit 1
        fi

    - name: Run go vet
      run: make vet

    - name: Run linter
      run: make lint
      continue-on-error: true  # 린터 오류가 있어도 CI가 실패하지 않도록

    - name: Security check
      run: make security
      continue-on-error: true  # 보안 검사 오류가 있어도 CI가 실패하지 않도록

  build:
    runs-on: ubuntu-latest
    needs: test
    
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
      run: |
        make build-arch GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ktail-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/ktail-${{ matrix.goos }}-${{ matrix.goarch }}*
        retention-days: 7
